import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe,it } from "node:test";
function read(path){return readFileSync(new URL(`../${path}`,import.meta.url),"utf8");}
describe("provider live gate contracts",()=>{
 it("requires every credential, verification, and operational gate before live delivery",()=>{const r=read("src/lib/adapters/readiness.ts");for(const key of ["LINE_CHANNEL_ACCESS_TOKEN","LINE_CHANNEL_SECRET","X_API_KEY","X_API_SECRET","X_ACCESS_TOKEN","X_ACCESS_TOKEN_SECRET","INSTAGRAM_PAGE_ACCESS_TOKEN","INSTAGRAM_APP_SECRET","LINE_PROVIDER_INBOUND_VERIFIED","LINE_PROVIDER_OUTBOUND_VERIFIED","X_PROVIDER_INBOUND_VERIFIED","X_PROVIDER_OUTBOUND_VERIFIED","INSTAGRAM_PROVIDER_INBOUND_VERIFIED","INSTAGRAM_PROVIDER_OUTBOUND_VERIFIED","COMMUNICATION_PLANNER_WEBHOOK_SIGNATURE_VERIFICATION","COMMUNICATION_PLANNER_PROVIDER_RATE_LIMIT_POLICY","COMMUNICATION_PLANNER_PROVIDER_ERROR_MAPPING"])assert.match(r,new RegExp(key));assert.match(r,/providerVerificationRequirements/);assert.match(r,/liveSendReady = blockers\.length === 0/);assert.match(r,/requestedDeliveryMode === "live" && liveSendReady \? "live" : "dry_run"/);});
 it("keeps provider verification flags visible in the env template",()=>{const env=read(".env.example");for(const key of ["LINE_PROVIDER_INBOUND_VERIFIED=disabled","LINE_PROVIDER_OUTBOUND_VERIFIED=disabled","X_PROVIDER_INBOUND_VERIFIED=disabled","X_PROVIDER_OUTBOUND_VERIFIED=disabled","INSTAGRAM_PROVIDER_INBOUND_VERIFIED=disabled","INSTAGRAM_PROVIDER_OUTBOUND_VERIFIED=disabled"])assert.match(env,new RegExp(key));});
 it("keeps provider verification gates visible in rollout and operator docs",()=>{const runbook=read("docs/production-deployment-runbook.md"),dashboard=read("docs/operator-dashboard.md"),adapterDoc=read("docs/channel-adapters.md"),oss=read("docs/oss-adoption.md");for(const key of ["LINE_PROVIDER_INBOUND_VERIFIED","LINE_PROVIDER_OUTBOUND_VERIFIED","X_PROVIDER_INBOUND_VERIFIED","X_PROVIDER_OUTBOUND_VERIFIED","INSTAGRAM_PROVIDER_INBOUND_VERIFIED","INSTAGRAM_PROVIDER_OUTBOUND_VERIFIED"])assert.match(runbook,new RegExp(key));assert.match(runbook,/provider-specific inbound\/outbound verification/);assert.match(dashboard,/providerVerificationRequirements/);assert.match(adapterDoc,/provider verification/);assert.match(adapterDoc,/providerVerificationRequirements/);assert.match(oss,/provider verification flags/);});
 it("keeps the deployment runbook current with the latest verified contract count",()=>{const runbook=read("docs/production-deployment-runbook.md");assert.match(runbook,/As of 2026-08-25/);assert.match(runbook,/50 tests across 15 suites/);assert.match(runbook,/Latest verified GitHub main checkpoint/);assert.doesNotMatch(runbook,/48 tests/);assert.doesNotMatch(runbook,/49 tests/);assert.doesNotMatch(runbook,/d4713dbdb829515c8a7ca2da21e9c11b9e15b60c/);});
 it("keeps readiness output boolean-only for secrets",()=>{const r=read("src/lib/adapters/readiness.ts"),route=read("src/app/api/adapters/readiness/route.ts");assert.match(r,/met: configured\(process\.env\[key\]\)/);assert.match(r,/met: secret\.configured/);assert.doesNotMatch(route,/process\.env/);assert.doesNotMatch(route,/ACCESS_TOKEN.*value|API_SECRET.*value|CHANNEL_SECRET.*value/);});
 it("keeps provider send routed through readiness, rate-limit, dry-run and error guards",()=>{const s=read("src/lib/adapters/send.ts");assert.match(s,/getProviderSendReadiness/);assert.match(s,/checkProviderRateLimit/);assert.match(s,/deliveryMode: readiness\.effectiveDeliveryMode/);assert.match(s,/if \(!rateLimit\.ok\)/);assert.match(s,/httpStatus: 429/);assert.match(s,/mapProviderError/);});
});
